services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./config/apache:/etc/apache2/sites-available
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=estacionamento
      - DB_USER=root
      - DB_PASS=root123
    networks:
      - estacionamento-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: estacionamento
      MYSQL_USER: estacionamento_user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - estacionamento-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root123
    depends_on:
      - db
    networks:
      - estacionamento-network

volumes:
  mysql_data:

networks:
  estacionamento-network:
    driver: bridge